### ISSUE TITLE
Preact benchmark

### ISSUE THREAD

**Issue by jpwesselink** [taobaofed/rx-ssr-compare#1]
Would be nice to see [Preact](https://preactjs.com/) added as well.

**Comment by developit** [comment]
I'd be willing to add it, but I am concerned with the way these benchmarks are written.  Looping a constant number of times over a function that returns the same value and is given the same input is unlikely to be an analog real-world performance.

**Comment by imsobear** [comment]
what about this #9 @jpwesselink

**Comment by jpwesselink** [comment]
Thanks for adding that :)

**Comment by developit** [comment]
Looks perfect! Not sure if the client diffing comment I made matters anyway since this is testing SSR perf. Hats off to you 🙇

**Comment by imsobear** [comment]
yeah, maybe we can create another repo to compare render performance in client.
